#include "thermostat_rt_mri_mri.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void thermostat_rt_mri_mri_initialize(void);
void thermostat_rt_mri_mri_notify(microkit_channel channel);
void thermostat_rt_mri_mri_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Temp_i_1_t *upper_desired_temp_queue_1;
volatile sb_queue_Isolette_Data_Model_Temp_i_1_t *lower_desired_temp_queue_1;
volatile sb_queue_Isolette_Data_Model_Temp_i_1_t *displayed_temp_queue_1;
volatile sb_queue_Isolette_Data_Model_Status_1_t *regulator_status_queue_1;
volatile sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *interface_failure_queue_1;
volatile sb_queue_Isolette_Data_Model_Regulator_Mode_1_t *regulator_mode_queue_1;
sb_queue_Isolette_Data_Model_Regulator_Mode_1_Recv_t regulator_mode_recv_queue;
volatile sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *lower_desired_tempWstatus_queue_1;
sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t lower_desired_tempWstatus_recv_queue;
volatile sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *upper_desired_tempWstatus_queue_1;
sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t upper_desired_tempWstatus_recv_queue;
volatile sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *current_tempWstatus_queue_1;
sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t current_tempWstatus_recv_queue;

#define PORT_FROM_MON 60

bool put_upper_desired_temp(const Isolette_Data_Model_Temp_i *data) {
  sb_queue_Isolette_Data_Model_Temp_i_1_enqueue((sb_queue_Isolette_Data_Model_Temp_i_1_t *) upper_desired_temp_queue_1, (Isolette_Data_Model_Temp_i *) data);

  return true;
}

bool put_lower_desired_temp(const Isolette_Data_Model_Temp_i *data) {
  sb_queue_Isolette_Data_Model_Temp_i_1_enqueue((sb_queue_Isolette_Data_Model_Temp_i_1_t *) lower_desired_temp_queue_1, (Isolette_Data_Model_Temp_i *) data);

  return true;
}

bool put_displayed_temp(const Isolette_Data_Model_Temp_i *data) {
  sb_queue_Isolette_Data_Model_Temp_i_1_enqueue((sb_queue_Isolette_Data_Model_Temp_i_1_t *) displayed_temp_queue_1, (Isolette_Data_Model_Temp_i *) data);

  return true;
}

bool put_regulator_status(const Isolette_Data_Model_Status *data) {
  sb_queue_Isolette_Data_Model_Status_1_enqueue((sb_queue_Isolette_Data_Model_Status_1_t *) regulator_status_queue_1, (Isolette_Data_Model_Status *) data);

  return true;
}

bool put_interface_failure(const Isolette_Data_Model_Failure_Flag_i *data) {
  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_enqueue((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) interface_failure_queue_1, (Isolette_Data_Model_Failure_Flag_i *) data);

  return true;
}

Isolette_Data_Model_Regulator_Mode last_regulator_mode_payload;

bool get_regulator_mode(Isolette_Data_Model_Regulator_Mode *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_Regulator_Mode fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_Regulator_Mode_1_dequeue((sb_queue_Isolette_Data_Model_Regulator_Mode_1_Recv_t *) &regulator_mode_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_regulator_mode_payload = fresh_data;
  }
  *data = last_regulator_mode_payload;
  return isFresh;
}

Isolette_Data_Model_TempWstatus_i last_lower_desired_tempWstatus_payload;

bool get_lower_desired_tempWstatus(Isolette_Data_Model_TempWstatus_i *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_TempWstatus_i fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_TempWstatus_i_1_dequeue((sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t *) &lower_desired_tempWstatus_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_lower_desired_tempWstatus_payload = fresh_data;
  }
  *data = last_lower_desired_tempWstatus_payload;
  return isFresh;
}

Isolette_Data_Model_TempWstatus_i last_upper_desired_tempWstatus_payload;

bool get_upper_desired_tempWstatus(Isolette_Data_Model_TempWstatus_i *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_TempWstatus_i fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_TempWstatus_i_1_dequeue((sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t *) &upper_desired_tempWstatus_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_upper_desired_tempWstatus_payload = fresh_data;
  }
  *data = last_upper_desired_tempWstatus_payload;
  return isFresh;
}

Isolette_Data_Model_TempWstatus_i last_current_tempWstatus_payload;

bool get_current_tempWstatus(Isolette_Data_Model_TempWstatus_i *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_TempWstatus_i fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_TempWstatus_i_1_dequeue((sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_t *) &current_tempWstatus_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_current_tempWstatus_payload = fresh_data;
  }
  *data = last_current_tempWstatus_payload;
  return isFresh;
}

void init(void) {
  sb_queue_Isolette_Data_Model_Temp_i_1_init((sb_queue_Isolette_Data_Model_Temp_i_1_t *) upper_desired_temp_queue_1);

  sb_queue_Isolette_Data_Model_Temp_i_1_init((sb_queue_Isolette_Data_Model_Temp_i_1_t *) lower_desired_temp_queue_1);

  sb_queue_Isolette_Data_Model_Temp_i_1_init((sb_queue_Isolette_Data_Model_Temp_i_1_t *) displayed_temp_queue_1);

  sb_queue_Isolette_Data_Model_Status_1_init((sb_queue_Isolette_Data_Model_Status_1_t *) regulator_status_queue_1);

  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_init((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) interface_failure_queue_1);

  sb_queue_Isolette_Data_Model_Regulator_Mode_1_Recv_init(&regulator_mode_recv_queue, (sb_queue_Isolette_Data_Model_Regulator_Mode_1_t *) regulator_mode_queue_1);

  sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_init(&lower_desired_tempWstatus_recv_queue, (sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *) lower_desired_tempWstatus_queue_1);

  sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_init(&upper_desired_tempWstatus_recv_queue, (sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *) upper_desired_tempWstatus_queue_1);

  sb_queue_Isolette_Data_Model_TempWstatus_i_1_Recv_init(&current_tempWstatus_recv_queue, (sb_queue_Isolette_Data_Model_TempWstatus_i_1_t *) current_tempWstatus_queue_1);

  thermostat_rt_mri_mri_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      thermostat_rt_mri_mri_timeTriggered();
      break;
    default:
      thermostat_rt_mri_mri_notify(channel);
  }
}
