# Do not edit this file as it will be overwritten if HAMR codegen is rerun

# Monitor configuration for runtime monitoring scheduler variant.
# Usage: make CONFIG=monitor.mk
export MSD := $(TOP_DIR)/meta.monitor.py
export SCHEDULER_C := $(TOP_DIR)/scheduler/src/monitor.scheduler.c
export SCHEDULER_CONFIG_HEADERS := $(TOP_DIR)/scheduler/include/monitor.user_config.h