# Do not edit this file as it will be overwritten if HAMR codegen is rerun

ifeq ($(strip $(LIONSOS)),)
$(error LIONSOS must be specified)
endif
override LIONSOS:=$(abspath ${LIONSOS})


# Metaprogram that generates the system description file.
# Override to use an alternative schedule (e.g. monitor.mk).
MSD ?= $(TOP_DIR)/meta.py

# Header files containing config structs whose sizes the sdfgen helper
# needs to calculate. Override to point at a different config header.
SCHEDULER_CONFIG_HEADERS ?= $(TOP_DIR)/scheduler/include/default.user_config.h

# Scheduler C source file compiled into scheduler.elf.
# Override to substitute a different scheduler implementation
# (e.g. one that publishes schedule state for runtime monitoring).
SCHEDULER_C ?= $(TOP_DIR)/scheduler/src/default.scheduler.c


TOOLCHAIN := clang
CC := clang
LD := ld.lld
RANLIB := llvm-ranlib
AR := llvm-ar
OBJCOPY := llvm-objcopy
MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit
DTC := dtc
PYTHON ?= python3
SDDF := $(LIONSOS)/dep/sddf

SYSTEM_FILE := arinc_scheduling.system
IMAGE_FILE := loader.img
REPORT_FILE := report.txt

SUPPORTED_BOARDS := qemu_virt_aarch64

include ${SDDF}/tools/make/board/common.mk

SDFGEN_HELPER := $(TOP_DIR)/sdfgen_helper.py

# Macros needed by sdfgen helper to calculate config struct sizes
SDFGEN_UNKOWN_MACROS := MAX_PARTITIONS=61 MAX_SCHEDULE_SLOTS=128

SDDF_CUSTOM_LIBC := 1

LDFLAGS := -L$(BOARD_DIR)/lib -L$(SDDF)/lib
LIBS := -lmicrokit -Tmicrokit.ld libsddf_util_debug.a

SDDF_MAKEFILES := ${SDDF}/util/util.mk \
	${SDDF}/drivers/timer/${TIMER_DRIV_DIR}/timer_driver.mk \
	${SDDF}/drivers/serial/${UART_DRIV_DIR}/serial_driver.mk \
	${SDDF}/serial/components/serial_components.mk

include ${SDDF_MAKEFILES}


CFLAGS += \
	-I$(LIONSOS)/include \
	-I$(SDDF)/include \
	-I$(SDDF)/include/microkit \
	-I$(TOP_DIR)/scheduler/include \
	-I$(TOP_DIR)/types/include \
	-I$(TOP_DIR)/components/thermostat_rt_mri_mri/include \
	-I$(TOP_DIR)/components/thermostat_rt_mhs_mhs/include \
	-I$(TOP_DIR)/components/thermostat_rt_mrm_mrm/include \
	-I$(TOP_DIR)/components/thermostat_rt_drf_drf/include \
	-I$(TOP_DIR)/components/thermostat_mt_mmi_mmi/include \
	-I$(TOP_DIR)/components/thermostat_mt_ma_ma/include \
	-I$(TOP_DIR)/components/thermostat_mt_mmm_mmm/include \
	-I$(TOP_DIR)/components/thermostat_mt_dmf_dmf/include \
	-I$(TOP_DIR)/components/operator_interface_oip_oit/include \
	-I$(TOP_DIR)/components/temperature_sensor_cpi_thermostat/include \
	-I$(TOP_DIR)/components/heat_source_cpi_heat_controller/include \
	-I$(TOP_DIR)/components/monitor_process_monitor_thread/include


UTIL_OBJS :=

TYPE_OBJS := \
	sb_queue_Isolette_Data_Model_Temp_i_1.o \
	sb_queue_Isolette_Data_Model_Status_1.o \
	sb_queue_Isolette_Data_Model_Failure_Flag_i_1.o \
	sb_queue_Isolette_Data_Model_On_Off_1.o \
	sb_queue_Isolette_Data_Model_Regulator_Mode_1.o \
	sb_queue_Isolette_Data_Model_Monitor_Mode_1.o \
	sb_queue_Isolette_Data_Model_TempWstatus_i_1.o \
	sb_queue_Isolette_Data_Model_PhysicalTemp_i_1.o \
	sb_queue_Isolette_Environment_Heat_1.o \
	sb_queue_hamr_SchedState_1.o \
	sb_queue_hamr_Schedule_1.o


all: cache.o

# Sentinel file whose name encodes a hash of CFLAGS, BOARD, and MICROKIT_CONFIG.
# When any of those change the old sentinel is removed and a new one is created,
# which can be used as a prerequisite to force recompilation.
CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@


vpath %.c $(SDDF) \
	$(TOP_DIR)/scheduler/src \
	$(TOP_DIR)/types/src \
	$(TOP_DIR)/components/thermostat_rt_mri_mri/src \
	$(TOP_DIR)/components/thermostat_rt_mhs_mhs/src \
	$(TOP_DIR)/components/thermostat_rt_mrm_mrm/src \
	$(TOP_DIR)/components/thermostat_rt_drf_drf/src \
	$(TOP_DIR)/components/thermostat_mt_mmi_mmi/src \
	$(TOP_DIR)/components/thermostat_mt_ma_ma/src \
	$(TOP_DIR)/components/thermostat_mt_mmm_mmm/src \
	$(TOP_DIR)/components/thermostat_mt_dmf_dmf/src \
	$(TOP_DIR)/components/operator_interface_oip_oit/src \
	$(TOP_DIR)/components/temperature_sensor_cpi_thermostat/src \
	$(TOP_DIR)/components/heat_source_cpi_heat_controller/src \
	$(TOP_DIR)/components/monitor_process_monitor_thread/src


IMAGES := timer_driver.elf scheduler.elf \
	thermostat_rt_mri_mri.elf \
	thermostat_rt_mri_mri_MON.elf \
	thermostat_rt_mhs_mhs.elf \
	thermostat_rt_mhs_mhs_MON.elf \
	thermostat_rt_mrm_mrm.elf \
	thermostat_rt_mrm_mrm_MON.elf \
	thermostat_rt_drf_drf.elf \
	thermostat_rt_drf_drf_MON.elf \
	thermostat_mt_mmi_mmi.elf \
	thermostat_mt_mmi_mmi_MON.elf \
	thermostat_mt_ma_ma.elf \
	thermostat_mt_ma_ma_MON.elf \
	thermostat_mt_mmm_mmm.elf \
	thermostat_mt_mmm_mmm_MON.elf \
	thermostat_mt_dmf_dmf.elf \
	thermostat_mt_dmf_dmf_MON.elf \
	operator_interface_oip_oit.elf \
	operator_interface_oip_oit_MON.elf \
	temperature_sensor_cpi_thermostat.elf \
	temperature_sensor_cpi_thermostat_MON.elf \
	heat_source_cpi_heat_controller.elf \
	heat_source_cpi_heat_controller_MON.elf \
	monitor_process_monitor_thread.elf \
	monitor_process_monitor_thread_MON.elf

${IMAGES}: libsddf_util_debug.a


# user code
thermostat_rt_mri_mri_rust:
	make -C ${CRATES_DIR}/thermostat_rt_mri_mri $(RUST_MAKE_TARGET)

# user code
thermostat_rt_mhs_mhs_rust:
	make -C ${CRATES_DIR}/thermostat_rt_mhs_mhs $(RUST_MAKE_TARGET)

# user code
thermostat_rt_mrm_mrm_rust:
	make -C ${CRATES_DIR}/thermostat_rt_mrm_mrm $(RUST_MAKE_TARGET)

# user code
thermostat_rt_drf_drf_rust:
	make -C ${CRATES_DIR}/thermostat_rt_drf_drf $(RUST_MAKE_TARGET)

# user code
thermostat_mt_mmi_mmi_rust:
	make -C ${CRATES_DIR}/thermostat_mt_mmi_mmi $(RUST_MAKE_TARGET)

# user code
thermostat_mt_ma_ma_rust:
	make -C ${CRATES_DIR}/thermostat_mt_ma_ma $(RUST_MAKE_TARGET)

# user code
thermostat_mt_mmm_mmm_rust:
	make -C ${CRATES_DIR}/thermostat_mt_mmm_mmm $(RUST_MAKE_TARGET)

# user code
thermostat_mt_dmf_dmf_rust:
	make -C ${CRATES_DIR}/thermostat_mt_dmf_dmf $(RUST_MAKE_TARGET)

# user code
operator_interface_oip_oit_rust:
	make -C ${CRATES_DIR}/operator_interface_oip_oit $(RUST_MAKE_TARGET)

# user code
monitor_process_monitor_thread_rust:
	make -C ${CRATES_DIR}/monitor_process_monitor_thread $(RUST_MAKE_TARGET)

%.o: %.c ${SDDF}/include
	${CC} ${CFLAGS} -c -o $@ $<

SCHEDULER_OBJ := $(notdir $(basename $(SCHEDULER_C))).o

$(SCHEDULER_OBJ): $(SCHEDULER_C) ${SDDF}/include
	${CC} ${CFLAGS} -c -o $@ $<

scheduler.elf: $(UTIL_OBJS) $(TYPE_OBJS) $(SCHEDULER_OBJ)
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_rt_mri_mri_MON.elf: thermostat_rt_mri_mri_MON_user.o thermostat_rt_mri_mri_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_rt_mri_mri.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_rt_mri_mri_rust thermostat_rt_mri_mri.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_rt_mri_mri/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_rt_mri_mri -o $@

thermostat_rt_mhs_mhs_MON.elf: thermostat_rt_mhs_mhs_MON_user.o thermostat_rt_mhs_mhs_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_rt_mhs_mhs.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_rt_mhs_mhs_rust thermostat_rt_mhs_mhs.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_rt_mhs_mhs/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_rt_mhs_mhs -o $@

thermostat_rt_mrm_mrm_MON.elf: thermostat_rt_mrm_mrm_MON_user.o thermostat_rt_mrm_mrm_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_rt_mrm_mrm.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_rt_mrm_mrm_rust thermostat_rt_mrm_mrm.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_rt_mrm_mrm/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_rt_mrm_mrm -o $@

thermostat_rt_drf_drf_MON.elf: thermostat_rt_drf_drf_MON_user.o thermostat_rt_drf_drf_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_rt_drf_drf.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_rt_drf_drf_rust thermostat_rt_drf_drf.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_rt_drf_drf/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_rt_drf_drf -o $@

thermostat_mt_mmi_mmi_MON.elf: thermostat_mt_mmi_mmi_MON_user.o thermostat_mt_mmi_mmi_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_mt_mmi_mmi.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_mt_mmi_mmi_rust thermostat_mt_mmi_mmi.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_mt_mmi_mmi/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_mt_mmi_mmi -o $@

thermostat_mt_ma_ma_MON.elf: thermostat_mt_ma_ma_MON_user.o thermostat_mt_ma_ma_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_mt_ma_ma.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_mt_ma_ma_rust thermostat_mt_ma_ma.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_mt_ma_ma/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_mt_ma_ma -o $@

thermostat_mt_mmm_mmm_MON.elf: thermostat_mt_mmm_mmm_MON_user.o thermostat_mt_mmm_mmm_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_mt_mmm_mmm.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_mt_mmm_mmm_rust thermostat_mt_mmm_mmm.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_mt_mmm_mmm/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_mt_mmm_mmm -o $@

thermostat_mt_dmf_dmf_MON.elf: thermostat_mt_dmf_dmf_MON_user.o thermostat_mt_dmf_dmf_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

thermostat_mt_dmf_dmf.elf: $(UTIL_OBJS) $(TYPE_OBJS) thermostat_mt_dmf_dmf_rust thermostat_mt_dmf_dmf.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/thermostat_mt_dmf_dmf/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lthermostat_mt_dmf_dmf -o $@

operator_interface_oip_oit_MON.elf: operator_interface_oip_oit_MON_user.o operator_interface_oip_oit_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

operator_interface_oip_oit.elf: $(UTIL_OBJS) $(TYPE_OBJS) operator_interface_oip_oit_rust operator_interface_oip_oit.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/operator_interface_oip_oit/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -loperator_interface_oip_oit -o $@

temperature_sensor_cpi_thermostat_MON.elf: temperature_sensor_cpi_thermostat_MON_user.o temperature_sensor_cpi_thermostat_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

temperature_sensor_cpi_thermostat.elf: $(UTIL_OBJS) $(TYPE_OBJS) temperature_sensor_cpi_thermostat_user.o temperature_sensor_cpi_thermostat.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

heat_source_cpi_heat_controller_MON.elf: heat_source_cpi_heat_controller_MON_user.o heat_source_cpi_heat_controller_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

heat_source_cpi_heat_controller.elf: $(UTIL_OBJS) $(TYPE_OBJS) heat_source_cpi_heat_controller_user.o heat_source_cpi_heat_controller.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

monitor_process_monitor_thread_MON.elf: monitor_process_monitor_thread_MON_user.o monitor_process_monitor_thread_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

monitor_process_monitor_thread.elf: $(UTIL_OBJS) $(TYPE_OBJS) monitor_process_monitor_thread_rust monitor_process_monitor_thread.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/monitor_process_monitor_thread/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lmonitor_process_monitor_thread -o $@



$(SYSTEM_FILE): $(MSD) $(IMAGES) $(DTB)
	$(PYTHON) $(SDFGEN_HELPER) --macros "$(SDFGEN_UNKOWN_MACROS)" --configs "$(SCHEDULER_CONFIG_HEADERS)" --output $(TOP_BUILD_DIR)/config_structs.py
	$(PYTHON) $(MSD) --sddf $(SDDF) --board $(MICROKIT_BOARD) --dtb $(DTB) --output . --sdf $(SYSTEM_FILE) --objcopy $(OBJCOPY)
	$(OBJCOPY) --update-section .device_resources=timer_driver_device_resources.data timer_driver.elf
	$(OBJCOPY) --update-section .timer_client_config=timer_client_scheduler.data scheduler.elf

$(IMAGE_FILE) $(REPORT_FILE): $(IMAGES) $(SYSTEM_FILE)
	$(MICROKIT_TOOL) $(SYSTEM_FILE) --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


FORCE:

qemu:
	$(QEMU) -nographic $(QEMU_ARCH_ARGS)

clean::
	${RM} -f *.elf .depend* $
	find . -name \*.[do] |xargs --no-run-if-empty rm

clobber:: clean
	rm -f *.a
	rm -f ${IMAGE_FILE} ${REPORT_FILE}

test:: 
	make -C ${CRATES_DIR}/thermostat_rt_mri_mri test
	make -C ${CRATES_DIR}/thermostat_rt_mhs_mhs test
	make -C ${CRATES_DIR}/thermostat_rt_mrm_mrm test
	make -C ${CRATES_DIR}/thermostat_rt_drf_drf test
	make -C ${CRATES_DIR}/thermostat_mt_mmi_mmi test
	make -C ${CRATES_DIR}/thermostat_mt_ma_ma test
	make -C ${CRATES_DIR}/thermostat_mt_mmm_mmm test
	make -C ${CRATES_DIR}/thermostat_mt_dmf_dmf test
	make -C ${CRATES_DIR}/operator_interface_oip_oit test
	make -C ${CRATES_DIR}/monitor_process_monitor_thread test

clean:: 
	make -C ${CRATES_DIR}/thermostat_rt_mri_mri clean
	make -C ${CRATES_DIR}/thermostat_rt_mhs_mhs clean
	make -C ${CRATES_DIR}/thermostat_rt_mrm_mrm clean
	make -C ${CRATES_DIR}/thermostat_rt_drf_drf clean
	make -C ${CRATES_DIR}/thermostat_mt_mmi_mmi clean
	make -C ${CRATES_DIR}/thermostat_mt_ma_ma clean
	make -C ${CRATES_DIR}/thermostat_mt_mmm_mmm clean
	make -C ${CRATES_DIR}/thermostat_mt_dmf_dmf clean
	make -C ${CRATES_DIR}/operator_interface_oip_oit clean
	make -C ${CRATES_DIR}/monitor_process_monitor_thread clean

verus: 
	make -C ${CRATES_DIR}/thermostat_rt_mri_mri verus
	make -C ${CRATES_DIR}/thermostat_rt_mhs_mhs verus
	make -C ${CRATES_DIR}/thermostat_rt_mrm_mrm verus
	make -C ${CRATES_DIR}/thermostat_rt_drf_drf verus
	make -C ${CRATES_DIR}/thermostat_mt_mmi_mmi verus
	make -C ${CRATES_DIR}/thermostat_mt_ma_ma verus
	make -C ${CRATES_DIR}/thermostat_mt_mmm_mmm verus
	make -C ${CRATES_DIR}/thermostat_mt_dmf_dmf verus
	make -C ${CRATES_DIR}/operator_interface_oip_oit verus
	make -C ${CRATES_DIR}/monitor_process_monitor_thread verus
