// #Sireum
package isolette.Regulate

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait Manage_Regulator_Interface_i_thermostat_rt_mri_mri_Injection_Provider {
  def pre_receiveInput(): Unit
}

object Manage_Regulator_Interface_i_thermostat_rt_mri_mri_Injection_Service {

  var providers: MSZ[Manage_Regulator_Interface_i_thermostat_rt_mri_mri_Injection_Provider] = MSZ()

  def register(provider: Manage_Regulator_Interface_i_thermostat_rt_mri_mri_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}