#include "thermostat_mt_dmf_dmf.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void thermostat_mt_dmf_dmf_initialize(void);
void thermostat_mt_dmf_dmf_notify(microkit_channel channel);
void thermostat_mt_dmf_dmf_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *internal_failure_queue_1;

#define PORT_FROM_MON 0

bool put_internal_failure(const Isolette_Data_Model_Failure_Flag_i *data) {
  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_enqueue((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) internal_failure_queue_1, (Isolette_Data_Model_Failure_Flag_i *) data);

  return true;
}

void init(void) {
  printf("%s | INIT!\n", microkit_name);

  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_init((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) internal_failure_queue_1);

  thermostat_mt_dmf_dmf_initialize();

  microkit_notify(PORT_FROM_MON);
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      thermostat_mt_dmf_dmf_timeTriggered();
      break;
    default:
      thermostat_mt_dmf_dmf_notify(channel);
  }
}
