// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum Regulator_Mode {
    pub Init_Regulator_Mode = 0,
    pub Normal_Regulator_Mode = 1,
    pub Failed_Regulator_Mode = 2,
  }

  impl Default for Regulator_Mode {
    fn default() -> Self
    {
      Regulator_Mode::Init_Regulator_Mode
    }
  }
}