// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use data::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct TempWstatus_i {
    pub degrees: i32,
    pub status: ValueStatus
  }

  impl Default for TempWstatus_i {
    fn default() -> Self 
    {
      Self { degrees: 0, status: Isolette_Data_Model::ValueStatus::default() }
    }
  }
}