// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::thermostat_rt_mri_mri_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_rt_mri_mri_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_displayed_temp = get_displayed_temp();
  let api_interface_failure = get_interface_failure();
  let api_lower_desired_temp = get_lower_desired_temp();
  let api_regulator_status = get_regulator_status();
  let api_upper_desired_temp = get_upper_desired_temp();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (api_displayed_temp, api_interface_failure, api_lower_desired_temp, api_regulator_status, api_upper_desired_temp) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_current_tempWstatus incoming data port
  * @param api_lower_desired_tempWstatus incoming data port
  * @param api_regulator_mode incoming data port
  * @param api_upper_desired_tempWstatus incoming data port
  */
pub fn testComputeCB(
  api_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_lower_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_regulator_mode: Isolette_Data_Model::Regulator_Mode,
  api_upper_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i) -> HarnessResult
{
  // Initialize the app
  crate::thermostat_rt_mri_mri_initialize();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (api_current_tempWstatus, api_lower_desired_tempWstatus, api_regulator_mode, api_upper_desired_tempWstatus) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_current_tempWstatus(api_current_tempWstatus);
  put_lower_desired_tempWstatus(api_lower_desired_tempWstatus);
  put_regulator_mode(api_regulator_mode);
  put_upper_desired_tempWstatus(api_upper_desired_tempWstatus);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_rt_mri_mri_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_displayed_temp = get_displayed_temp();
  let api_interface_failure = get_interface_failure();
  let api_lower_desired_temp = get_lower_desired_temp();
  let api_regulator_status = get_regulator_status();
  let api_upper_desired_temp = get_upper_desired_temp();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(api_current_tempWstatus, api_lower_desired_tempWstatus, api_regulator_mode, api_upper_desired_tempWstatus, api_displayed_temp, api_interface_failure, api_lower_desired_temp, api_regulator_status, api_upper_desired_temp) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_current_tempWstatus, container.api_lower_desired_tempWstatus, container.api_regulator_mode, container.api_upper_desired_tempWstatus)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_current_tempWstatus: $api_current_tempWstatus_strat:expr,
    api_lower_desired_tempWstatus: $api_lower_desired_tempWstatus_strat:expr,
    api_regulator_mode: $api_regulator_mode_strat:expr,
    api_upper_desired_tempWstatus: $api_upper_desired_tempWstatus_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_current_tempWstatus, api_lower_desired_tempWstatus, api_regulator_mode, api_upper_desired_tempWstatus)
            in ($api_current_tempWstatus_strat, $api_lower_desired_tempWstatus_strat, $api_regulator_mode_strat, $api_upper_desired_tempWstatus_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_current_tempWstatus, api_lower_desired_tempWstatus, api_regulator_mode, api_upper_desired_tempWstatus) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
