// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use data::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Failure_Flag_i {
    pub flag: bool
  }

  impl Default for Failure_Flag_i {
    fn default() -> Self 
    {
      Self { flag: false }
    }
  }
}