// #Sireum

package isolette.Devices

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import isolette.GumboXUtil.GumboXResult
import isolette.util.{Container, Profile, UnitTestConfigurationBatch}
import isolette.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Heat_Source_i_heat_source_cpi_heat_controller_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultComputeProfile = Heat_Source_i_heat_source_cpi_heat_controller_Profile_P

  def defaultComputeConfig: Heat_Source_i_heat_source_cpi_heat_controller_Compute_UnitTestConfiguration = {
    return (Heat_Source_i_heat_source_cpi_heat_controller_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Heat_Source_i_heat_source_cpi_heat_controller_Profile_P (
        name = "Compute_Default_Profile",
        api_heat_control = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = isolette.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${isolette.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = isolette.JSON.toDevicesHeat_Source_i_heat_source_cpi_heat_controller_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Heat_Source_i_heat_source_cpi_heat_controller_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Heat_Source_i_heat_source_cpi_heat_controller_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Heat_Source_i_heat_source_cpi_heat_controller_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Heat_Source_i_heat_source_cpi_heat_controller_PreState_Container])
  }
}
