// #Sireum

package isolette.Devices

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import isolette.GumboXUtil.GumboXResult
import isolette.util.{Container, Profile, UnitTestConfigurationBatch}
import isolette.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Temperature_Sensor_i_temperature_sensor_cpi_thermostat_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultInitializeProfile = Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile

  def defaultInitializeConfig: Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Initialize_UnitTestConfiguration = {
    return (Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile (
        name = "Initialize_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => None())
    )
  }

  type DefaultComputeProfile = Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile_P

  def defaultComputeConfig: Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Compute_UnitTestConfiguration = {
    return (Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile_P (
        name = "Compute_Default_Profile",
        api_air = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = isolette.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${isolette.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = isolette.JSON.toDevicesTemperature_Sensor_i_temperature_sensor_cpi_thermostat_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Temperature_Sensor_i_temperature_sensor_cpi_thermostat_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Temperature_Sensor_i_temperature_sensor_cpi_thermostat_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Temperature_Sensor_i_temperature_sensor_cpi_thermostat_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Temperature_Sensor_i_temperature_sensor_cpi_thermostat_PreState_Container])
  }
}
