// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use data::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Temp_i {
    pub degrees: i32
  }

  impl Default for Temp_i {
    fn default() -> Self 
    {
      Self { degrees: 0 }
    }
  }
}