#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool get_interface_failure(Isolette_Data_Model_Failure_Flag_i *data);
bool put_monitor_mode(const Isolette_Data_Model_Monitor_Mode *data);
bool get_internal_failure(Isolette_Data_Model_Failure_Flag_i *data);
bool get_current_tempWstatus(Isolette_Data_Model_TempWstatus_i *data);
