// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum Heat {
    pub Dummy_Head_Enum = 0,
  }

  impl Default for Heat {
    fn default() -> Self
    {
      Heat::Dummy_Head_Enum
    }
  }
}