// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::thermostat_rt_mrm_mrm_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_rt_mrm_mrm_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let lastRegulatorMode = get_lastRegulatorMode();
  let api_regulator_mode = get_regulator_mode();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (lastRegulatorMode, api_regulator_mode) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_current_tempWstatus incoming data port
  * @param api_interface_failure incoming data port
  * @param api_internal_failure incoming data port
  */
pub fn testComputeCB(
  api_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_interface_failure: Isolette_Data_Model::Failure_Flag_i,
  api_internal_failure: Isolette_Data_Model::Failure_Flag_i) -> HarnessResult
{
  // Initialize the app
  crate::thermostat_rt_mrm_mrm_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_lastRegulatorMode: Isolette_Data_Model::Regulator_Mode = get_lastRegulatorMode();

  // [PutInPorts]: Set values on the input ports
  put_current_tempWstatus(api_current_tempWstatus);
  put_interface_failure(api_interface_failure);
  put_internal_failure(api_internal_failure);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_rt_mrm_mrm_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let lastRegulatorMode = get_lastRegulatorMode();
  let api_regulator_mode = get_regulator_mode();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_lastRegulatorMode, lastRegulatorMode, api_current_tempWstatus, api_interface_failure, api_internal_failure, api_regulator_mode) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_current_tempWstatus, container.api_interface_failure, container.api_internal_failure)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_current_tempWstatus: $api_current_tempWstatus_strat:expr,
    api_interface_failure: $api_interface_failure_strat:expr,
    api_internal_failure: $api_internal_failure_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_current_tempWstatus, api_interface_failure, api_internal_failure)
            in ($api_current_tempWstatus_strat, $api_interface_failure_strat, $api_internal_failure_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_current_tempWstatus, api_interface_failure, api_internal_failure) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_lastRegulatorMode pre-state state variable
  * @param api_current_tempWstatus incoming data port
  * @param api_interface_failure incoming data port
  * @param api_internal_failure incoming data port
  */
pub fn testComputeCBwGSV(
  In_lastRegulatorMode: Isolette_Data_Model::Regulator_Mode,
  api_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_interface_failure: Isolette_Data_Model::Failure_Flag_i,
  api_internal_failure: Isolette_Data_Model::Failure_Flag_i) -> HarnessResult
{
  // Initialize the app
  crate::thermostat_rt_mrm_mrm_initialize();

  // [PutInPorts]: Set values on the input ports
  put_current_tempWstatus(api_current_tempWstatus);
  put_interface_failure(api_interface_failure);
  put_internal_failure(api_internal_failure);

  // [SetInStateVars]: set the pre-state values of state variables
  put_lastRegulatorMode(In_lastRegulatorMode);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_rt_mrm_mrm_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let lastRegulatorMode = get_lastRegulatorMode();
  let api_regulator_mode = get_regulator_mode();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_lastRegulatorMode, lastRegulatorMode, api_current_tempWstatus, api_interface_failure, api_internal_failure, api_regulator_mode) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_lastRegulatorMode, container.api_current_tempWstatus, container.api_interface_failure, container.api_internal_failure)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_lastRegulatorMode: $In_lastRegulatorMode_strat:expr,
    api_current_tempWstatus: $api_current_tempWstatus_strat:expr,
    api_interface_failure: $api_interface_failure_strat:expr,
    api_internal_failure: $api_internal_failure_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (In_lastRegulatorMode, api_current_tempWstatus, api_interface_failure, api_internal_failure)
            in ($In_lastRegulatorMode_strat, $api_current_tempWstatus_strat, $api_interface_failure_strat, $api_internal_failure_strat)
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_lastRegulatorMode, api_current_tempWstatus, api_interface_failure, api_internal_failure) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
