// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_mri_mri_displayed_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool;
  fn get_mri_mri_regulator_status(value: *mut Isolette_Data_Model::Status) -> bool;
  fn get_mhs_mhs_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool;
  fn get_mmi_mmi_monitor_status(value: *mut Isolette_Data_Model::Status) -> bool;
  fn get_ma_ma_alarm_control(value: *mut Isolette_Data_Model::On_Off) -> bool;
  fn get_oip_oit_lower_desired_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool;
  fn get_oip_oit_upper_desired_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool;
  fn get_oip_oit_lower_alarm_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool;
  fn get_oip_oit_upper_alarm_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool;
  fn get_cpi_thermostat_current_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool;
  fn get_mri_mri_upper_desired_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool;
  fn get_mri_mri_lower_desired_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool;
  fn get_mri_mri_interface_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool;
  fn get_mrm_mrm_regulator_mode(value: *mut Isolette_Data_Model::Regulator_Mode) -> bool;
  fn get_drf_drf_internal_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool;
  fn get_mmi_mmi_upper_alarm_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool;
  fn get_mmi_mmi_lower_alarm_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool;
  fn get_mmi_mmi_interface_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool;
  fn get_mmm_mmm_monitor_mode(value: *mut Isolette_Data_Model::Monitor_Mode) -> bool;
  fn get_dmf_dmf_internal_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool;
  fn get_sched_state(value: *mut hamr::SchedState) -> bool;
  fn get_sched_schedule(value: *mut hamr::Schedule) -> bool;
  fn get_mhs_mhs_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool;
  fn get_mrm_mrm_sv_lastRegulatorMode(value: *mut Isolette_Data_Model::Regulator_Mode) -> bool;
  fn get_mmi_mmi_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool;
  fn get_ma_ma_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool;
  fn get_mmm_mmm_sv_lastMonitorMode(value: *mut Isolette_Data_Model::Monitor_Mode) -> bool;
}

pub fn unsafe_get_mri_mri_displayed_temp() -> Isolette_Data_Model::Temp_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp_i = &mut Isolette_Data_Model::Temp_i::default();
    get_mri_mri_displayed_temp(value);
    return *value;
  }
}

pub fn unsafe_get_mri_mri_regulator_status() -> Isolette_Data_Model::Status
{
  unsafe {
    let value: *mut Isolette_Data_Model::Status = &mut Isolette_Data_Model::Status::default();
    get_mri_mri_regulator_status(value);
    return *value;
  }
}

pub fn unsafe_get_mhs_mhs_heat_control() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_mhs_mhs_heat_control(value);
    return *value;
  }
}

pub fn unsafe_get_mmi_mmi_monitor_status() -> Isolette_Data_Model::Status
{
  unsafe {
    let value: *mut Isolette_Data_Model::Status = &mut Isolette_Data_Model::Status::default();
    get_mmi_mmi_monitor_status(value);
    return *value;
  }
}

pub fn unsafe_get_ma_ma_alarm_control() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_ma_ma_alarm_control(value);
    return *value;
  }
}

pub fn unsafe_get_oip_oit_lower_desired_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::TempWstatus_i = &mut Isolette_Data_Model::TempWstatus_i::default();
    get_oip_oit_lower_desired_tempWstatus(value);
    return *value;
  }
}

pub fn unsafe_get_oip_oit_upper_desired_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::TempWstatus_i = &mut Isolette_Data_Model::TempWstatus_i::default();
    get_oip_oit_upper_desired_tempWstatus(value);
    return *value;
  }
}

pub fn unsafe_get_oip_oit_lower_alarm_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::TempWstatus_i = &mut Isolette_Data_Model::TempWstatus_i::default();
    get_oip_oit_lower_alarm_tempWstatus(value);
    return *value;
  }
}

pub fn unsafe_get_oip_oit_upper_alarm_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::TempWstatus_i = &mut Isolette_Data_Model::TempWstatus_i::default();
    get_oip_oit_upper_alarm_tempWstatus(value);
    return *value;
  }
}

pub fn unsafe_get_cpi_thermostat_current_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::TempWstatus_i = &mut Isolette_Data_Model::TempWstatus_i::default();
    get_cpi_thermostat_current_tempWstatus(value);
    return *value;
  }
}

pub fn unsafe_get_mri_mri_upper_desired_temp() -> Isolette_Data_Model::Temp_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp_i = &mut Isolette_Data_Model::Temp_i::default();
    get_mri_mri_upper_desired_temp(value);
    return *value;
  }
}

pub fn unsafe_get_mri_mri_lower_desired_temp() -> Isolette_Data_Model::Temp_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp_i = &mut Isolette_Data_Model::Temp_i::default();
    get_mri_mri_lower_desired_temp(value);
    return *value;
  }
}

pub fn unsafe_get_mri_mri_interface_failure() -> Isolette_Data_Model::Failure_Flag_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Failure_Flag_i = &mut Isolette_Data_Model::Failure_Flag_i::default();
    get_mri_mri_interface_failure(value);
    return *value;
  }
}

pub fn unsafe_get_mrm_mrm_regulator_mode() -> Isolette_Data_Model::Regulator_Mode
{
  unsafe {
    let value: *mut Isolette_Data_Model::Regulator_Mode = &mut Isolette_Data_Model::Regulator_Mode::default();
    get_mrm_mrm_regulator_mode(value);
    return *value;
  }
}

pub fn unsafe_get_drf_drf_internal_failure() -> Isolette_Data_Model::Failure_Flag_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Failure_Flag_i = &mut Isolette_Data_Model::Failure_Flag_i::default();
    get_drf_drf_internal_failure(value);
    return *value;
  }
}

pub fn unsafe_get_mmi_mmi_upper_alarm_temp() -> Isolette_Data_Model::Temp_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp_i = &mut Isolette_Data_Model::Temp_i::default();
    get_mmi_mmi_upper_alarm_temp(value);
    return *value;
  }
}

pub fn unsafe_get_mmi_mmi_lower_alarm_temp() -> Isolette_Data_Model::Temp_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp_i = &mut Isolette_Data_Model::Temp_i::default();
    get_mmi_mmi_lower_alarm_temp(value);
    return *value;
  }
}

pub fn unsafe_get_mmi_mmi_interface_failure() -> Isolette_Data_Model::Failure_Flag_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Failure_Flag_i = &mut Isolette_Data_Model::Failure_Flag_i::default();
    get_mmi_mmi_interface_failure(value);
    return *value;
  }
}

pub fn unsafe_get_mmm_mmm_monitor_mode() -> Isolette_Data_Model::Monitor_Mode
{
  unsafe {
    let value: *mut Isolette_Data_Model::Monitor_Mode = &mut Isolette_Data_Model::Monitor_Mode::default();
    get_mmm_mmm_monitor_mode(value);
    return *value;
  }
}

pub fn unsafe_get_dmf_dmf_internal_failure() -> Isolette_Data_Model::Failure_Flag_i
{
  unsafe {
    let value: *mut Isolette_Data_Model::Failure_Flag_i = &mut Isolette_Data_Model::Failure_Flag_i::default();
    get_dmf_dmf_internal_failure(value);
    return *value;
  }
}

pub fn unsafe_get_sched_state() -> hamr::SchedState
{
  unsafe {
    let value: *mut hamr::SchedState = &mut hamr::SchedState::default();
    get_sched_state(value);
    return *value;
  }
}

pub fn unsafe_get_sched_schedule() -> hamr::Schedule
{
  unsafe {
    let value: *mut hamr::Schedule = &mut hamr::Schedule::default();
    get_sched_schedule(value);
    return *value;
  }
}

pub fn unsafe_get_mhs_mhs_sv_lastCmd() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_mhs_mhs_sv_lastCmd(value);
    return *value;
  }
}

pub fn unsafe_get_mrm_mrm_sv_lastRegulatorMode() -> Isolette_Data_Model::Regulator_Mode
{
  unsafe {
    let value: *mut Isolette_Data_Model::Regulator_Mode = &mut Isolette_Data_Model::Regulator_Mode::default();
    get_mrm_mrm_sv_lastRegulatorMode(value);
    return *value;
  }
}

pub fn unsafe_get_mmi_mmi_sv_lastCmd() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_mmi_mmi_sv_lastCmd(value);
    return *value;
  }
}

pub fn unsafe_get_ma_ma_sv_lastCmd() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_ma_ma_sv_lastCmd(value);
    return *value;
  }
}

pub fn unsafe_get_mmm_mmm_sv_lastMonitorMode() -> Isolette_Data_Model::Monitor_Mode
{
  unsafe {
    let value: *mut Isolette_Data_Model::Monitor_Mode = &mut Isolette_Data_Model::Monitor_Mode::default();
    get_mmm_mmm_sv_lastMonitorMode(value);
    return *value;
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_mri_mri_displayed_temp: Mutex<Option<Isolette_Data_Model::Temp_i>> = Mutex::new(None);
  pub static ref IN_mri_mri_regulator_status: Mutex<Option<Isolette_Data_Model::Status>> = Mutex::new(None);
  pub static ref IN_mhs_mhs_heat_control: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
  pub static ref IN_mmi_mmi_monitor_status: Mutex<Option<Isolette_Data_Model::Status>> = Mutex::new(None);
  pub static ref IN_ma_ma_alarm_control: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
  pub static ref IN_oip_oit_lower_desired_tempWstatus: Mutex<Option<Isolette_Data_Model::TempWstatus_i>> = Mutex::new(None);
  pub static ref IN_oip_oit_upper_desired_tempWstatus: Mutex<Option<Isolette_Data_Model::TempWstatus_i>> = Mutex::new(None);
  pub static ref IN_oip_oit_lower_alarm_tempWstatus: Mutex<Option<Isolette_Data_Model::TempWstatus_i>> = Mutex::new(None);
  pub static ref IN_oip_oit_upper_alarm_tempWstatus: Mutex<Option<Isolette_Data_Model::TempWstatus_i>> = Mutex::new(None);
  pub static ref IN_cpi_thermostat_current_tempWstatus: Mutex<Option<Isolette_Data_Model::TempWstatus_i>> = Mutex::new(None);
  pub static ref IN_mri_mri_upper_desired_temp: Mutex<Option<Isolette_Data_Model::Temp_i>> = Mutex::new(None);
  pub static ref IN_mri_mri_lower_desired_temp: Mutex<Option<Isolette_Data_Model::Temp_i>> = Mutex::new(None);
  pub static ref IN_mri_mri_interface_failure: Mutex<Option<Isolette_Data_Model::Failure_Flag_i>> = Mutex::new(None);
  pub static ref IN_mrm_mrm_regulator_mode: Mutex<Option<Isolette_Data_Model::Regulator_Mode>> = Mutex::new(None);
  pub static ref IN_drf_drf_internal_failure: Mutex<Option<Isolette_Data_Model::Failure_Flag_i>> = Mutex::new(None);
  pub static ref IN_mmi_mmi_upper_alarm_temp: Mutex<Option<Isolette_Data_Model::Temp_i>> = Mutex::new(None);
  pub static ref IN_mmi_mmi_lower_alarm_temp: Mutex<Option<Isolette_Data_Model::Temp_i>> = Mutex::new(None);
  pub static ref IN_mmi_mmi_interface_failure: Mutex<Option<Isolette_Data_Model::Failure_Flag_i>> = Mutex::new(None);
  pub static ref IN_mmm_mmm_monitor_mode: Mutex<Option<Isolette_Data_Model::Monitor_Mode>> = Mutex::new(None);
  pub static ref IN_dmf_dmf_internal_failure: Mutex<Option<Isolette_Data_Model::Failure_Flag_i>> = Mutex::new(None);
  pub static ref IN_sched_state: Mutex<Option<hamr::SchedState>> = Mutex::new(None);
  pub static ref IN_sched_schedule: Mutex<Option<hamr::Schedule>> = Mutex::new(None);
  pub static ref IN_mhs_mhs_sv_lastCmd: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
  pub static ref IN_mrm_mrm_sv_lastRegulatorMode: Mutex<Option<Isolette_Data_Model::Regulator_Mode>> = Mutex::new(None);
  pub static ref IN_mmi_mmi_sv_lastCmd: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
  pub static ref IN_ma_ma_sv_lastCmd: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
  pub static ref IN_mmm_mmm_sv_lastMonitorMode: Mutex<Option<Isolette_Data_Model::Monitor_Mode>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_mri_mri_displayed_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mri_mri_regulator_status.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mhs_mhs_heat_control.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmi_mmi_monitor_status.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_ma_ma_alarm_control.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_oip_oit_lower_desired_tempWstatus.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_oip_oit_upper_desired_tempWstatus.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_oip_oit_lower_alarm_tempWstatus.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_oip_oit_upper_alarm_tempWstatus.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_cpi_thermostat_current_tempWstatus.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mri_mri_upper_desired_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mri_mri_lower_desired_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mri_mri_interface_failure.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mrm_mrm_regulator_mode.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_drf_drf_internal_failure.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmi_mmi_upper_alarm_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmi_mmi_lower_alarm_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmi_mmi_interface_failure.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmm_mmm_monitor_mode.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_dmf_dmf_internal_failure.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_sched_state.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_sched_schedule.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mhs_mhs_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mrm_mrm_sv_lastRegulatorMode.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmi_mmi_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_ma_ma_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_mmm_mmm_sv_lastMonitorMode.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_mri_mri_displayed_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool
{
  unsafe {
    let guard = IN_mri_mri_displayed_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mri_mri_regulator_status(value: *mut Isolette_Data_Model::Status) -> bool
{
  unsafe {
    let guard = IN_mri_mri_regulator_status.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mhs_mhs_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    let guard = IN_mhs_mhs_heat_control.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmi_mmi_monitor_status(value: *mut Isolette_Data_Model::Status) -> bool
{
  unsafe {
    let guard = IN_mmi_mmi_monitor_status.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_ma_ma_alarm_control(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    let guard = IN_ma_ma_alarm_control.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_oip_oit_lower_desired_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool
{
  unsafe {
    let guard = IN_oip_oit_lower_desired_tempWstatus.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_oip_oit_upper_desired_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool
{
  unsafe {
    let guard = IN_oip_oit_upper_desired_tempWstatus.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_oip_oit_lower_alarm_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool
{
  unsafe {
    let guard = IN_oip_oit_lower_alarm_tempWstatus.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_oip_oit_upper_alarm_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool
{
  unsafe {
    let guard = IN_oip_oit_upper_alarm_tempWstatus.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_cpi_thermostat_current_tempWstatus(value: *mut Isolette_Data_Model::TempWstatus_i) -> bool
{
  unsafe {
    let guard = IN_cpi_thermostat_current_tempWstatus.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mri_mri_upper_desired_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool
{
  unsafe {
    let guard = IN_mri_mri_upper_desired_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mri_mri_lower_desired_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool
{
  unsafe {
    let guard = IN_mri_mri_lower_desired_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mri_mri_interface_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool
{
  unsafe {
    let guard = IN_mri_mri_interface_failure.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mrm_mrm_regulator_mode(value: *mut Isolette_Data_Model::Regulator_Mode) -> bool
{
  unsafe {
    let guard = IN_mrm_mrm_regulator_mode.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_drf_drf_internal_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool
{
  unsafe {
    let guard = IN_drf_drf_internal_failure.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmi_mmi_upper_alarm_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool
{
  unsafe {
    let guard = IN_mmi_mmi_upper_alarm_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmi_mmi_lower_alarm_temp(value: *mut Isolette_Data_Model::Temp_i) -> bool
{
  unsafe {
    let guard = IN_mmi_mmi_lower_alarm_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmi_mmi_interface_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool
{
  unsafe {
    let guard = IN_mmi_mmi_interface_failure.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmm_mmm_monitor_mode(value: *mut Isolette_Data_Model::Monitor_Mode) -> bool
{
  unsafe {
    let guard = IN_mmm_mmm_monitor_mode.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_dmf_dmf_internal_failure(value: *mut Isolette_Data_Model::Failure_Flag_i) -> bool
{
  unsafe {
    let guard = IN_dmf_dmf_internal_failure.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_sched_state(value: *mut hamr::SchedState) -> bool
{
  unsafe {
    let guard = IN_sched_state.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_sched_schedule(value: *mut hamr::Schedule) -> bool
{
  unsafe {
    let guard = IN_sched_schedule.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mhs_mhs_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    let guard = IN_mhs_mhs_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mrm_mrm_sv_lastRegulatorMode(value: *mut Isolette_Data_Model::Regulator_Mode) -> bool
{
  unsafe {
    let guard = IN_mrm_mrm_sv_lastRegulatorMode.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmi_mmi_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    let guard = IN_mmi_mmi_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_ma_ma_sv_lastCmd(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    let guard = IN_ma_ma_sv_lastCmd.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_mmm_mmm_sv_lastMonitorMode(value: *mut Isolette_Data_Model::Monitor_Mode) -> bool
{
  unsafe {
    let guard = IN_mmm_mmm_sv_lastMonitorMode.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}
