// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait monitor_process_monitor_thread_Api {}

  pub trait monitor_process_monitor_thread_Put_Api: monitor_process_monitor_thread_Api {
  }

  pub trait monitor_process_monitor_thread_Get_Api: monitor_process_monitor_thread_Api {
    #[verifier::external_body]
    fn unverified_get_mri_mri_displayed_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp_i>) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mri_mri_displayed_temp();
    }

    #[verifier::external_body]
    fn unverified_get_mri_mri_regulator_status(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Status>) -> (res : Isolette_Data_Model::Status)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mri_mri_regulator_status();
    }

    #[verifier::external_body]
    fn unverified_get_mhs_mhs_heat_control(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mhs_mhs_heat_control();
    }

    #[verifier::external_body]
    fn unverified_get_mmi_mmi_monitor_status(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Status>) -> (res : Isolette_Data_Model::Status)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmi_mmi_monitor_status();
    }

    #[verifier::external_body]
    fn unverified_get_ma_ma_alarm_control(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_ma_ma_alarm_control();
    }

    #[verifier::external_body]
    fn unverified_get_oip_oit_lower_desired_tempWstatus(
      &mut self,
      value: &Ghost<Isolette_Data_Model::TempWstatus_i>) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_oip_oit_lower_desired_tempWstatus();
    }

    #[verifier::external_body]
    fn unverified_get_oip_oit_upper_desired_tempWstatus(
      &mut self,
      value: &Ghost<Isolette_Data_Model::TempWstatus_i>) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_oip_oit_upper_desired_tempWstatus();
    }

    #[verifier::external_body]
    fn unverified_get_oip_oit_lower_alarm_tempWstatus(
      &mut self,
      value: &Ghost<Isolette_Data_Model::TempWstatus_i>) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_oip_oit_lower_alarm_tempWstatus();
    }

    #[verifier::external_body]
    fn unverified_get_oip_oit_upper_alarm_tempWstatus(
      &mut self,
      value: &Ghost<Isolette_Data_Model::TempWstatus_i>) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_oip_oit_upper_alarm_tempWstatus();
    }

    #[verifier::external_body]
    fn unverified_get_cpi_thermostat_current_tempWstatus(
      &mut self,
      value: &Ghost<Isolette_Data_Model::TempWstatus_i>) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_cpi_thermostat_current_tempWstatus();
    }

    #[verifier::external_body]
    fn unverified_get_mri_mri_upper_desired_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp_i>) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mri_mri_upper_desired_temp();
    }

    #[verifier::external_body]
    fn unverified_get_mri_mri_lower_desired_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp_i>) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mri_mri_lower_desired_temp();
    }

    #[verifier::external_body]
    fn unverified_get_mri_mri_interface_failure(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Failure_Flag_i>) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mri_mri_interface_failure();
    }

    #[verifier::external_body]
    fn unverified_get_mrm_mrm_regulator_mode(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Regulator_Mode>) -> (res : Isolette_Data_Model::Regulator_Mode)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mrm_mrm_regulator_mode();
    }

    #[verifier::external_body]
    fn unverified_get_drf_drf_internal_failure(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Failure_Flag_i>) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_drf_drf_internal_failure();
    }

    #[verifier::external_body]
    fn unverified_get_mmi_mmi_upper_alarm_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp_i>) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmi_mmi_upper_alarm_temp();
    }

    #[verifier::external_body]
    fn unverified_get_mmi_mmi_lower_alarm_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp_i>) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmi_mmi_lower_alarm_temp();
    }

    #[verifier::external_body]
    fn unverified_get_mmi_mmi_interface_failure(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Failure_Flag_i>) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmi_mmi_interface_failure();
    }

    #[verifier::external_body]
    fn unverified_get_mmm_mmm_monitor_mode(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Monitor_Mode>) -> (res : Isolette_Data_Model::Monitor_Mode)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmm_mmm_monitor_mode();
    }

    #[verifier::external_body]
    fn unverified_get_dmf_dmf_internal_failure(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Failure_Flag_i>) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_dmf_dmf_internal_failure();
    }

    #[verifier::external_body]
    fn unverified_get_sched_state(
      &mut self,
      value: &Ghost<hamr::SchedState>) -> (res : hamr::SchedState)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_sched_state();
    }

    #[verifier::external_body]
    fn unverified_get_sched_schedule(
      &mut self,
      value: &Ghost<hamr::Schedule>) -> (res : hamr::Schedule)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_sched_schedule();
    }

    #[verifier::external_body]
    fn unverified_get_mhs_mhs_sv_lastCmd(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mhs_mhs_sv_lastCmd();
    }

    #[verifier::external_body]
    fn unverified_get_mrm_mrm_sv_lastRegulatorMode(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Regulator_Mode>) -> (res : Isolette_Data_Model::Regulator_Mode)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mrm_mrm_sv_lastRegulatorMode();
    }

    #[verifier::external_body]
    fn unverified_get_mmi_mmi_sv_lastCmd(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmi_mmi_sv_lastCmd();
    }

    #[verifier::external_body]
    fn unverified_get_ma_ma_sv_lastCmd(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_ma_ma_sv_lastCmd();
    }

    #[verifier::external_body]
    fn unverified_get_mmm_mmm_sv_lastMonitorMode(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Monitor_Mode>) -> (res : Isolette_Data_Model::Monitor_Mode)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_mmm_mmm_sv_lastMonitorMode();
    }
  }

  pub trait monitor_process_monitor_thread_Full_Api: monitor_process_monitor_thread_Put_Api + monitor_process_monitor_thread_Get_Api {}

  pub struct monitor_process_monitor_thread_Application_Api<API: monitor_process_monitor_thread_Api> {
    pub api: API,

    pub ghost mri_mri_displayed_temp: Isolette_Data_Model::Temp_i,
    pub ghost mri_mri_regulator_status: Isolette_Data_Model::Status,
    pub ghost mhs_mhs_heat_control: Isolette_Data_Model::On_Off,
    pub ghost mmi_mmi_monitor_status: Isolette_Data_Model::Status,
    pub ghost ma_ma_alarm_control: Isolette_Data_Model::On_Off,
    pub ghost oip_oit_lower_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub ghost oip_oit_upper_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub ghost oip_oit_lower_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub ghost oip_oit_upper_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub ghost cpi_thermostat_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub ghost mri_mri_upper_desired_temp: Isolette_Data_Model::Temp_i,
    pub ghost mri_mri_lower_desired_temp: Isolette_Data_Model::Temp_i,
    pub ghost mri_mri_interface_failure: Isolette_Data_Model::Failure_Flag_i,
    pub ghost mrm_mrm_regulator_mode: Isolette_Data_Model::Regulator_Mode,
    pub ghost drf_drf_internal_failure: Isolette_Data_Model::Failure_Flag_i,
    pub ghost mmi_mmi_upper_alarm_temp: Isolette_Data_Model::Temp_i,
    pub ghost mmi_mmi_lower_alarm_temp: Isolette_Data_Model::Temp_i,
    pub ghost mmi_mmi_interface_failure: Isolette_Data_Model::Failure_Flag_i,
    pub ghost mmm_mmm_monitor_mode: Isolette_Data_Model::Monitor_Mode,
    pub ghost dmf_dmf_internal_failure: Isolette_Data_Model::Failure_Flag_i,
    pub ghost sched_state: hamr::SchedState,
    pub ghost sched_schedule: hamr::Schedule,
    pub ghost mhs_mhs_sv_lastCmd: Isolette_Data_Model::On_Off,
    pub ghost mrm_mrm_sv_lastRegulatorMode: Isolette_Data_Model::Regulator_Mode,
    pub ghost mmi_mmi_sv_lastCmd: Isolette_Data_Model::On_Off,
    pub ghost ma_ma_sv_lastCmd: Isolette_Data_Model::On_Off,
    pub ghost mmm_mmm_sv_lastMonitorMode: Isolette_Data_Model::Monitor_Mode
  }

  impl<API: monitor_process_monitor_thread_Put_Api> monitor_process_monitor_thread_Application_Api<API> {
  }

  impl<API: monitor_process_monitor_thread_Get_Api> monitor_process_monitor_thread_Application_Api<API> {
    pub fn get_mri_mri_displayed_temp(&mut self) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        res == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mri_mri_displayed_temp(&Ghost(self.mri_mri_displayed_temp))
    }
    pub fn get_mri_mri_regulator_status(&mut self) -> (res : Isolette_Data_Model::Status)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        res == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mri_mri_regulator_status(&Ghost(self.mri_mri_regulator_status))
    }
    pub fn get_mhs_mhs_heat_control(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        res == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mhs_mhs_heat_control(&Ghost(self.mhs_mhs_heat_control))
    }
    pub fn get_mmi_mmi_monitor_status(&mut self) -> (res : Isolette_Data_Model::Status)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        res == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmi_mmi_monitor_status(&Ghost(self.mmi_mmi_monitor_status))
    }
    pub fn get_ma_ma_alarm_control(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        res == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_ma_ma_alarm_control(&Ghost(self.ma_ma_alarm_control))
    }
    pub fn get_oip_oit_lower_desired_tempWstatus(&mut self) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        res == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_oip_oit_lower_desired_tempWstatus(&Ghost(self.oip_oit_lower_desired_tempWstatus))
    }
    pub fn get_oip_oit_upper_desired_tempWstatus(&mut self) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        res == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_oip_oit_upper_desired_tempWstatus(&Ghost(self.oip_oit_upper_desired_tempWstatus))
    }
    pub fn get_oip_oit_lower_alarm_tempWstatus(&mut self) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        res == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_oip_oit_lower_alarm_tempWstatus(&Ghost(self.oip_oit_lower_alarm_tempWstatus))
    }
    pub fn get_oip_oit_upper_alarm_tempWstatus(&mut self) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        res == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_oip_oit_upper_alarm_tempWstatus(&Ghost(self.oip_oit_upper_alarm_tempWstatus))
    }
    pub fn get_cpi_thermostat_current_tempWstatus(&mut self) -> (res : Isolette_Data_Model::TempWstatus_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        res == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_cpi_thermostat_current_tempWstatus(&Ghost(self.cpi_thermostat_current_tempWstatus))
    }
    pub fn get_mri_mri_upper_desired_temp(&mut self) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        res == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mri_mri_upper_desired_temp(&Ghost(self.mri_mri_upper_desired_temp))
    }
    pub fn get_mri_mri_lower_desired_temp(&mut self) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        res == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mri_mri_lower_desired_temp(&Ghost(self.mri_mri_lower_desired_temp))
    }
    pub fn get_mri_mri_interface_failure(&mut self) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        res == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mri_mri_interface_failure(&Ghost(self.mri_mri_interface_failure))
    }
    pub fn get_mrm_mrm_regulator_mode(&mut self) -> (res : Isolette_Data_Model::Regulator_Mode)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        res == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mrm_mrm_regulator_mode(&Ghost(self.mrm_mrm_regulator_mode))
    }
    pub fn get_drf_drf_internal_failure(&mut self) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        res == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_drf_drf_internal_failure(&Ghost(self.drf_drf_internal_failure))
    }
    pub fn get_mmi_mmi_upper_alarm_temp(&mut self) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        res == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmi_mmi_upper_alarm_temp(&Ghost(self.mmi_mmi_upper_alarm_temp))
    }
    pub fn get_mmi_mmi_lower_alarm_temp(&mut self) -> (res : Isolette_Data_Model::Temp_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        res == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmi_mmi_lower_alarm_temp(&Ghost(self.mmi_mmi_lower_alarm_temp))
    }
    pub fn get_mmi_mmi_interface_failure(&mut self) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        res == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmi_mmi_interface_failure(&Ghost(self.mmi_mmi_interface_failure))
    }
    pub fn get_mmm_mmm_monitor_mode(&mut self) -> (res : Isolette_Data_Model::Monitor_Mode)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        res == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmm_mmm_monitor_mode(&Ghost(self.mmm_mmm_monitor_mode))
    }
    pub fn get_dmf_dmf_internal_failure(&mut self) -> (res : Isolette_Data_Model::Failure_Flag_i)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        res == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_dmf_dmf_internal_failure(&Ghost(self.dmf_dmf_internal_failure))
    }
    pub fn get_sched_state(&mut self) -> (res : hamr::SchedState)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        res == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_sched_state(&Ghost(self.sched_state))
    }
    pub fn get_sched_schedule(&mut self) -> (res : hamr::Schedule)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        res == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_sched_schedule(&Ghost(self.sched_schedule))
    }
    pub fn get_mhs_mhs_sv_lastCmd(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        res == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mhs_mhs_sv_lastCmd(&Ghost(self.mhs_mhs_sv_lastCmd))
    }
    pub fn get_mrm_mrm_sv_lastRegulatorMode(&mut self) -> (res : Isolette_Data_Model::Regulator_Mode)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        res == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mrm_mrm_sv_lastRegulatorMode(&Ghost(self.mrm_mrm_sv_lastRegulatorMode))
    }
    pub fn get_mmi_mmi_sv_lastCmd(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        res == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmi_mmi_sv_lastCmd(&Ghost(self.mmi_mmi_sv_lastCmd))
    }
    pub fn get_ma_ma_sv_lastCmd(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        res == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_ma_ma_sv_lastCmd(&Ghost(self.ma_ma_sv_lastCmd))
    }
    pub fn get_mmm_mmm_sv_lastMonitorMode(&mut self) -> (res : Isolette_Data_Model::Monitor_Mode)
      ensures
        old(self).mri_mri_displayed_temp == self.mri_mri_displayed_temp,
        old(self).mri_mri_regulator_status == self.mri_mri_regulator_status,
        old(self).mhs_mhs_heat_control == self.mhs_mhs_heat_control,
        old(self).mmi_mmi_monitor_status == self.mmi_mmi_monitor_status,
        old(self).ma_ma_alarm_control == self.ma_ma_alarm_control,
        old(self).oip_oit_lower_desired_tempWstatus == self.oip_oit_lower_desired_tempWstatus,
        old(self).oip_oit_upper_desired_tempWstatus == self.oip_oit_upper_desired_tempWstatus,
        old(self).oip_oit_lower_alarm_tempWstatus == self.oip_oit_lower_alarm_tempWstatus,
        old(self).oip_oit_upper_alarm_tempWstatus == self.oip_oit_upper_alarm_tempWstatus,
        old(self).cpi_thermostat_current_tempWstatus == self.cpi_thermostat_current_tempWstatus,
        old(self).mri_mri_upper_desired_temp == self.mri_mri_upper_desired_temp,
        old(self).mri_mri_lower_desired_temp == self.mri_mri_lower_desired_temp,
        old(self).mri_mri_interface_failure == self.mri_mri_interface_failure,
        old(self).mrm_mrm_regulator_mode == self.mrm_mrm_regulator_mode,
        old(self).drf_drf_internal_failure == self.drf_drf_internal_failure,
        old(self).mmi_mmi_upper_alarm_temp == self.mmi_mmi_upper_alarm_temp,
        old(self).mmi_mmi_lower_alarm_temp == self.mmi_mmi_lower_alarm_temp,
        old(self).mmi_mmi_interface_failure == self.mmi_mmi_interface_failure,
        old(self).mmm_mmm_monitor_mode == self.mmm_mmm_monitor_mode,
        old(self).dmf_dmf_internal_failure == self.dmf_dmf_internal_failure,
        old(self).sched_state == self.sched_state,
        old(self).sched_schedule == self.sched_schedule,
        old(self).mhs_mhs_sv_lastCmd == self.mhs_mhs_sv_lastCmd,
        old(self).mrm_mrm_sv_lastRegulatorMode == self.mrm_mrm_sv_lastRegulatorMode,
        old(self).mmi_mmi_sv_lastCmd == self.mmi_mmi_sv_lastCmd,
        old(self).ma_ma_sv_lastCmd == self.ma_ma_sv_lastCmd,
        old(self).mmm_mmm_sv_lastMonitorMode == self.mmm_mmm_sv_lastMonitorMode,
        res == self.mmm_mmm_sv_lastMonitorMode,
    {
      self.api.unverified_get_mmm_mmm_sv_lastMonitorMode(&Ghost(self.mmm_mmm_sv_lastMonitorMode))
    }
  }

  pub struct monitor_process_monitor_thread_Initialization_Api;
  impl monitor_process_monitor_thread_Api for monitor_process_monitor_thread_Initialization_Api {}
  impl monitor_process_monitor_thread_Put_Api for monitor_process_monitor_thread_Initialization_Api {}

  pub const fn init_api() -> monitor_process_monitor_thread_Application_Api<monitor_process_monitor_thread_Initialization_Api> {
    return monitor_process_monitor_thread_Application_Api {
      api: monitor_process_monitor_thread_Initialization_Api {},

      mri_mri_displayed_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_regulator_status: Isolette_Data_Model::Status::Init_Status,
      mhs_mhs_heat_control: Isolette_Data_Model::On_Off::Onn,
      mmi_mmi_monitor_status: Isolette_Data_Model::Status::Init_Status,
      ma_ma_alarm_control: Isolette_Data_Model::On_Off::Onn,
      oip_oit_lower_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_upper_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_lower_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_upper_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      cpi_thermostat_current_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      mri_mri_upper_desired_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_lower_desired_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_interface_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mrm_mrm_regulator_mode: Isolette_Data_Model::Regulator_Mode::Init_Regulator_Mode,
      drf_drf_internal_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mmi_mmi_upper_alarm_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mmi_mmi_lower_alarm_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mmi_mmi_interface_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mmm_mmm_monitor_mode: Isolette_Data_Model::Monitor_Mode::Init_Monitor_Mode,
      dmf_dmf_internal_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      sched_state: hamr::SchedState { last_yielded_ch: 0, next_dispatch_ch: 0, current_timeslice: 0 },
      sched_schedule: hamr::Schedule { timeslices: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], timeslice_ch: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], is_user_partition: [false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false], num_timeslices: 0 },
      mhs_mhs_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      mrm_mrm_sv_lastRegulatorMode: Isolette_Data_Model::Regulator_Mode::Init_Regulator_Mode,
      mmi_mmi_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      ma_ma_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      mmm_mmm_sv_lastMonitorMode: Isolette_Data_Model::Monitor_Mode::Init_Monitor_Mode
    }
  }

  pub struct monitor_process_monitor_thread_Compute_Api;
  impl monitor_process_monitor_thread_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Put_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Get_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Full_Api for monitor_process_monitor_thread_Compute_Api {}

  pub const fn compute_api() -> monitor_process_monitor_thread_Application_Api<monitor_process_monitor_thread_Compute_Api> {
    return monitor_process_monitor_thread_Application_Api {
      api: monitor_process_monitor_thread_Compute_Api {},

      mri_mri_displayed_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_regulator_status: Isolette_Data_Model::Status::Init_Status,
      mhs_mhs_heat_control: Isolette_Data_Model::On_Off::Onn,
      mmi_mmi_monitor_status: Isolette_Data_Model::Status::Init_Status,
      ma_ma_alarm_control: Isolette_Data_Model::On_Off::Onn,
      oip_oit_lower_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_upper_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_lower_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      oip_oit_upper_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      cpi_thermostat_current_tempWstatus: Isolette_Data_Model::TempWstatus_i { degrees: 0, status: Isolette_Data_Model::ValueStatus::Valid },
      mri_mri_upper_desired_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_lower_desired_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mri_mri_interface_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mrm_mrm_regulator_mode: Isolette_Data_Model::Regulator_Mode::Init_Regulator_Mode,
      drf_drf_internal_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mmi_mmi_upper_alarm_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mmi_mmi_lower_alarm_temp: Isolette_Data_Model::Temp_i { degrees: 0 },
      mmi_mmi_interface_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      mmm_mmm_monitor_mode: Isolette_Data_Model::Monitor_Mode::Init_Monitor_Mode,
      dmf_dmf_internal_failure: Isolette_Data_Model::Failure_Flag_i { flag: false },
      sched_state: hamr::SchedState { last_yielded_ch: 0, next_dispatch_ch: 0, current_timeslice: 0 },
      sched_schedule: hamr::Schedule { timeslices: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], timeslice_ch: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], is_user_partition: [false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false], num_timeslices: 0 },
      mhs_mhs_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      mrm_mrm_sv_lastRegulatorMode: Isolette_Data_Model::Regulator_Mode::Init_Regulator_Mode,
      mmi_mmi_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      ma_ma_sv_lastCmd: Isolette_Data_Model::On_Off::Onn,
      mmm_mmm_sv_lastMonitorMode: Isolette_Data_Model::Monitor_Mode::Init_Monitor_Mode
    }
  }
}