// #Sireum

package isolette.Operator_Interface

import org.sireum._
import isolette._
import org.sireum.S32._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object Operator_Interface_Thread_i_operator_interface_oip_oit_GumboX {
  /** I-Guar: Integration constraint on oit's outgoing data port lower_alarm_tempWstatus
    *
    * guarantee Allowed_LowerAlarmTempWstatus
    *   Table_A_12_LowerAlarmTemp: Range [96..101]:
    *   https://www.faa.gov/sites/faa.gov/files/aircraft/air_cert/design_approvals/air_software/AR-08-32.pdf#page=112 
    */
  @strictpure def I_Guar_lower_alarm_tempWstatus(lower_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    GUMBO_Library.GUMBO__Library.isValidTempWstatus(lower_alarm_tempWstatus) __>:
      s32"96" <= lower_alarm_tempWstatus.degrees &
        lower_alarm_tempWstatus.degrees <= s32"101"

  // I_Guar-Guard: Integration constraint on oit's outgoing data port lower_alarm_tempWstatus
  @strictpure def I_Guar_Guard_lower_alarm_tempWstatus(lower_alarm_tempWstatus: Option[Isolette_Data_Model.TempWstatus_i]): B =
    lower_alarm_tempWstatus.nonEmpty ___>: I_Guar_lower_alarm_tempWstatus(lower_alarm_tempWstatus.get)

  /** I-Guar: Integration constraint on oit's outgoing data port upper_alarm_tempWstatus
    *
    * guarantee Allowed_UpperAlarmTempWstatus
    *   Table_A_12_UpperAlarmTemp: Range [97..102]
    *   https://www.faa.gov/sites/faa.gov/files/aircraft/air_cert/design_approvals/air_software/AR-08-32.pdf#page=112 
    */
  @strictpure def I_Guar_upper_alarm_tempWstatus(upper_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    Operator_Interface_Thread_i_operator_interface_oip_oit.Allowed_UpperAlarmTempWStatus(upper_alarm_tempWstatus)

  // I_Guar-Guard: Integration constraint on oit's outgoing data port upper_alarm_tempWstatus
  @strictpure def I_Guar_Guard_upper_alarm_tempWstatus(upper_alarm_tempWstatus: Option[Isolette_Data_Model.TempWstatus_i]): B =
    upper_alarm_tempWstatus.nonEmpty ___>: I_Guar_upper_alarm_tempWstatus(upper_alarm_tempWstatus.get)

  /** IEP-Post: Initialize Entrypoint Post-Condition
    *
    * @param api_lower_alarm_tempWstatus outgoing data port
    * @param api_lower_desired_tempWstatus outgoing data port
    * @param api_upper_alarm_tempWstatus outgoing data port
    * @param api_upper_desired_tempWstatus outgoing data port
    */
  @strictpure def inititialize_IEP_Post (
      api_lower_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_lower_desired_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_desired_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with oit's state variables and outgoing ports
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_lower_alarm_tempWstatus) &
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_lower_desired_tempWstatus) &
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_upper_alarm_tempWstatus) &
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_upper_desired_tempWstatus) & 

     // I-Guar-Guard: Integration constraints for oit's outgoing ports"
     I_Guar_lower_alarm_tempWstatus(api_lower_alarm_tempWstatus) &
     I_Guar_upper_alarm_tempWstatus(api_upper_alarm_tempWstatus))

  /** IEP-Post: Initialize Entrypoint Post-Condition via container
    *
    * @param post Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def inititialize_IEP_Post_Container (post: Operator_Interface_Thread_i_operator_interface_oip_oit_PostState_Container_PS): B =
    inititialize_IEP_Post (
      api_lower_alarm_tempWstatus = post.api_lower_alarm_tempWstatus,
      api_lower_desired_tempWstatus = post.api_lower_desired_tempWstatus,
      api_upper_alarm_tempWstatus = post.api_upper_alarm_tempWstatus,
      api_upper_desired_tempWstatus = post.api_upper_desired_tempWstatus)

  /** CEP-Pre: Compute Entrypoint Pre-Condition for oit
    *
    * @param api_alarm_control incoming data port
    * @param api_display_temperature incoming data port
    * @param api_monitor_status incoming data port
    * @param api_regulator_status incoming data port
    */
  @strictpure def compute_CEP_Pre (
      api_alarm_control: Isolette_Data_Model.On_Off.Type,
      api_display_temperature: Isolette_Data_Model.Temp_i,
      api_monitor_status: Isolette_Data_Model.Status.Type,
      api_regulator_status: Isolette_Data_Model.Status.Type): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with oit's state variables and incoming ports
     Isolette_Data_Model.Temp_i.D_Inv_Temp_i(api_display_temperature))

  /** CEP-Pre: Compute Entrypoint Pre-Condition for oit via container
    *
    * @param pre Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def compute_CEP_Pre_Container(pre: Operator_Interface_Thread_i_operator_interface_oip_oit_PreState_Container_PS): B =
    compute_CEP_Pre(
      api_alarm_control = pre.api_alarm_control,
      api_display_temperature = pre.api_display_temperature,
      api_monitor_status = pre.api_monitor_status,
      api_regulator_status = pre.api_regulator_status)

  /** Compute Entrypoint Contract
    *
    * guarantee Allowed_AlarmTempWStatus_Ranges
    *   An integration constraint can only refer to a single port, so need a general requires
    *   clause to relate the lower and upper temps
    * @param api_lower_alarm_tempWstatus outgoing data port
    * @param api_upper_alarm_tempWstatus outgoing data port
    */
  @strictpure def compute_spec_Allowed_AlarmTempWStatus_Ranges_guarantee(
      api_lower_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    GUMBO_Library.GUMBO__Library.Allowed_AlarmTempWStatus_Ranges(api_lower_alarm_tempWstatus, api_upper_alarm_tempWstatus)

  /** CEP-T-Guar: Top-level guarantee contracts for oit's compute entrypoint
    *
    * @param api_lower_alarm_tempWstatus outgoing data port
    * @param api_upper_alarm_tempWstatus outgoing data port
    */
  @strictpure def compute_CEP_T_Guar (
      api_lower_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    compute_spec_Allowed_AlarmTempWStatus_Ranges_guarantee(api_lower_alarm_tempWstatus, api_upper_alarm_tempWstatus)

  /** CEP-Post: Compute Entrypoint Post-Condition for oit
    *
    * @param api_alarm_control incoming data port
    * @param api_display_temperature incoming data port
    * @param api_monitor_status incoming data port
    * @param api_regulator_status incoming data port
    * @param api_lower_alarm_tempWstatus outgoing data port
    * @param api_lower_desired_tempWstatus outgoing data port
    * @param api_upper_alarm_tempWstatus outgoing data port
    * @param api_upper_desired_tempWstatus outgoing data port
    */
  @strictpure def compute_CEP_Post (
      api_alarm_control: Isolette_Data_Model.On_Off.Type,
      api_display_temperature: Isolette_Data_Model.Temp_i,
      api_monitor_status: Isolette_Data_Model.Status.Type,
      api_regulator_status: Isolette_Data_Model.Status.Type,
      api_lower_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_lower_desired_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_alarm_tempWstatus: Isolette_Data_Model.TempWstatus_i,
      api_upper_desired_tempWstatus: Isolette_Data_Model.TempWstatus_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with oit's state variables and outgoing ports
     Isolette_Data_Model.Temp_i.D_Inv_Temp_i(api_display_temperature) & 
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_lower_alarm_tempWstatus) & 
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_lower_desired_tempWstatus) & 
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_upper_alarm_tempWstatus) & 
     Isolette_Data_Model.TempWstatus_i.D_Inv_TempWstatus_i(api_upper_desired_tempWstatus) & 

     // I-Guar-Guard: Integration constraints for oit's outgoing ports
     I_Guar_lower_alarm_tempWstatus(api_lower_alarm_tempWstatus) & 
     I_Guar_upper_alarm_tempWstatus(api_upper_alarm_tempWstatus) & 

     // CEP-Guar: guarantee clauses of oit's compute entrypoint
     compute_CEP_T_Guar (api_lower_alarm_tempWstatus, api_upper_alarm_tempWstatus))

  /** CEP-Post: Compute Entrypoint Post-Condition for oit via containers
    *
    * @param pre Container holding the values of incoming ports and the pre-state values of state variables
    * @param post Container holding the values of outgoing ports and the post-state values of state variables
    */
  @strictpure def compute_CEP_Post_Container(
      pre: Operator_Interface_Thread_i_operator_interface_oip_oit_PreState_Container_PS,
      post: Operator_Interface_Thread_i_operator_interface_oip_oit_PostState_Container_PS): B =
    compute_CEP_Post(
      api_alarm_control = pre.api_alarm_control,
      api_display_temperature = pre.api_display_temperature,
      api_monitor_status = pre.api_monitor_status,
      api_regulator_status = pre.api_regulator_status,
      api_lower_alarm_tempWstatus = post.api_lower_alarm_tempWstatus,
      api_lower_desired_tempWstatus = post.api_lower_desired_tempWstatus,
      api_upper_alarm_tempWstatus = post.api_upper_alarm_tempWstatus,
      api_upper_desired_tempWstatus = post.api_upper_desired_tempWstatus)
}
