#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

typedef
  enum {Valid, Invalid} Isolette_Data_Model_ValueStatus;

typedef
  enum {Init_Regulator_Mode, Normal_Regulator_Mode, Failed_Regulator_Mode} Isolette_Data_Model_Regulator_Mode;

typedef
  enum {Init_Status, On_Status, Failed_Status} Isolette_Data_Model_Status;

typedef
  enum {Onn, Off} Isolette_Data_Model_On_Off;

typedef
  enum {Init_Monitor_Mode, Normal_Monitor_Mode, Failed_Monitor_Mode} Isolette_Data_Model_Monitor_Mode;

typedef
  enum {Dummy_Head_Enum} Isolette_Environment_Heat;

typedef struct Isolette_Data_Model_Temp_i {
  int32_t degrees;
} Isolette_Data_Model_Temp_i;

typedef struct Isolette_Data_Model_PhysicalTemp_i {
  int32_t degrees;
} Isolette_Data_Model_PhysicalTemp_i;

typedef struct Isolette_Data_Model_TempWstatus_i {
  int32_t degrees;
  Isolette_Data_Model_ValueStatus status;
} Isolette_Data_Model_TempWstatus_i;

typedef struct Isolette_Data_Model_Failure_Flag_i {
  bool flag;
} Isolette_Data_Model_Failure_Flag_i;

#define hamr_ScheduleUserPartitions_BYTE_SIZE 128
#define hamr_ScheduleUserPartitions_DIM_0 128

typedef bool hamr_ScheduleUserPartitions [hamr_ScheduleUserPartitions_DIM_0];

typedef struct hamr_SchedState {
  uint32_t last_yielded_ch;
  uint32_t next_dispatch_ch;
  uint32_t current_timeslice;
} hamr_SchedState;

#define hamr_ScheduleChannels_BYTE_SIZE 512
#define hamr_ScheduleChannels_DIM_0 128

typedef uint32_t hamr_ScheduleChannels [hamr_ScheduleChannels_DIM_0];

#define hamr_ScheduleTimeslices_BYTE_SIZE 1024
#define hamr_ScheduleTimeslices_DIM_0 128

typedef uint64_t hamr_ScheduleTimeslices [hamr_ScheduleTimeslices_DIM_0];

typedef struct hamr_Schedule {
  hamr_ScheduleTimeslices timeslices;
  hamr_ScheduleChannels timeslice_ch;
  hamr_ScheduleUserPartitions is_user_partition;
  uint32_t num_timeslices;
} hamr_Schedule;
