#include "thermostat_rt_drf_drf.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void thermostat_rt_drf_drf_initialize(void);
void thermostat_rt_drf_drf_notify(microkit_channel channel);
void thermostat_rt_drf_drf_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *internal_failure_queue_1;

#define PORT_FROM_MON 54

bool put_internal_failure(const Isolette_Data_Model_Failure_Flag_i *data) {
  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_enqueue((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) internal_failure_queue_1, (Isolette_Data_Model_Failure_Flag_i *) data);

  return true;
}

void init(void) {
  sb_queue_Isolette_Data_Model_Failure_Flag_i_1_init((sb_queue_Isolette_Data_Model_Failure_Flag_i_1_t *) internal_failure_queue_1);

  thermostat_rt_drf_drf_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      thermostat_rt_drf_drf_timeTriggered();
      break;
    default:
      thermostat_rt_drf_drf_notify(channel);
  }
}
