#pragma once

#if __has_include("util.h")
#include <util.h>
#elif __has_include("libvmm/util/util.h")
#include <libvmm/util/util.h>
#elif __has_include("sddf/util/util.h")
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#endif

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_heat_control(Isolette_Data_Model_On_Off *data);
bool put_heat_out(const Isolette_Environment_Heat *data);
