// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::monitor_process_monitor_thread_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::monitor_process_monitor_thread_initialize();

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_cpi_thermostat_current_tempWstatus incoming data port
  * @param api_dmf_dmf_internal_failure incoming data port
  * @param api_drf_drf_internal_failure incoming data port
  * @param api_ma_ma_alarm_control incoming data port
  * @param api_mhs_mhs_heat_control incoming data port
  * @param api_mmi_mmi_interface_failure incoming data port
  * @param api_mmi_mmi_lower_alarm_temp incoming data port
  * @param api_mmi_mmi_monitor_status incoming data port
  * @param api_mmi_mmi_upper_alarm_temp incoming data port
  * @param api_mmm_mmm_monitor_mode incoming data port
  * @param api_mri_mri_displayed_temp incoming data port
  * @param api_mri_mri_interface_failure incoming data port
  * @param api_mri_mri_lower_desired_temp incoming data port
  * @param api_mri_mri_regulator_status incoming data port
  * @param api_mri_mri_upper_desired_temp incoming data port
  * @param api_mrm_mrm_regulator_mode incoming data port
  * @param api_oip_oit_lower_alarm_tempWstatus incoming data port
  * @param api_oip_oit_lower_desired_tempWstatus incoming data port
  * @param api_oip_oit_upper_alarm_tempWstatus incoming data port
  * @param api_oip_oit_upper_desired_tempWstatus incoming data port
  * @param api_sched_schedule incoming data port
  * @param api_sched_state incoming data port
  */
pub fn testComputeCB(
  api_cpi_thermostat_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_dmf_dmf_internal_failure: Isolette_Data_Model::Failure_Flag_i,
  api_drf_drf_internal_failure: Isolette_Data_Model::Failure_Flag_i,
  api_ma_ma_alarm_control: Isolette_Data_Model::On_Off,
  api_mhs_mhs_heat_control: Isolette_Data_Model::On_Off,
  api_mmi_mmi_interface_failure: Isolette_Data_Model::Failure_Flag_i,
  api_mmi_mmi_lower_alarm_temp: Isolette_Data_Model::Temp_i,
  api_mmi_mmi_monitor_status: Isolette_Data_Model::Status,
  api_mmi_mmi_upper_alarm_temp: Isolette_Data_Model::Temp_i,
  api_mmm_mmm_monitor_mode: Isolette_Data_Model::Monitor_Mode,
  api_mri_mri_displayed_temp: Isolette_Data_Model::Temp_i,
  api_mri_mri_interface_failure: Isolette_Data_Model::Failure_Flag_i,
  api_mri_mri_lower_desired_temp: Isolette_Data_Model::Temp_i,
  api_mri_mri_regulator_status: Isolette_Data_Model::Status,
  api_mri_mri_upper_desired_temp: Isolette_Data_Model::Temp_i,
  api_mrm_mrm_regulator_mode: Isolette_Data_Model::Regulator_Mode,
  api_oip_oit_lower_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_oip_oit_lower_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_oip_oit_upper_alarm_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_oip_oit_upper_desired_tempWstatus: Isolette_Data_Model::TempWstatus_i,
  api_sched_schedule: hamr::Schedule,
  api_sched_state: hamr::SchedState) -> HarnessResult
{
  // Initialize the app
  crate::monitor_process_monitor_thread_initialize();

  // [PutInPorts]: Set values on the input ports
  put_cpi_thermostat_current_tempWstatus(api_cpi_thermostat_current_tempWstatus);
  put_dmf_dmf_internal_failure(api_dmf_dmf_internal_failure);
  put_drf_drf_internal_failure(api_drf_drf_internal_failure);
  put_ma_ma_alarm_control(api_ma_ma_alarm_control);
  put_mhs_mhs_heat_control(api_mhs_mhs_heat_control);
  put_mmi_mmi_interface_failure(api_mmi_mmi_interface_failure);
  put_mmi_mmi_lower_alarm_temp(api_mmi_mmi_lower_alarm_temp);
  put_mmi_mmi_monitor_status(api_mmi_mmi_monitor_status);
  put_mmi_mmi_upper_alarm_temp(api_mmi_mmi_upper_alarm_temp);
  put_mmm_mmm_monitor_mode(api_mmm_mmm_monitor_mode);
  put_mri_mri_displayed_temp(api_mri_mri_displayed_temp);
  put_mri_mri_interface_failure(api_mri_mri_interface_failure);
  put_mri_mri_lower_desired_temp(api_mri_mri_lower_desired_temp);
  put_mri_mri_regulator_status(api_mri_mri_regulator_status);
  put_mri_mri_upper_desired_temp(api_mri_mri_upper_desired_temp);
  put_mrm_mrm_regulator_mode(api_mrm_mrm_regulator_mode);
  put_oip_oit_lower_alarm_tempWstatus(api_oip_oit_lower_alarm_tempWstatus);
  put_oip_oit_lower_desired_tempWstatus(api_oip_oit_lower_desired_tempWstatus);
  put_oip_oit_upper_alarm_tempWstatus(api_oip_oit_upper_alarm_tempWstatus);
  put_oip_oit_upper_desired_tempWstatus(api_oip_oit_upper_desired_tempWstatus);
  put_sched_schedule(api_sched_schedule);
  put_sched_state(api_sched_state);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::monitor_process_monitor_thread_timeTriggered();

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_cpi_thermostat_current_tempWstatus, container.api_dmf_dmf_internal_failure, container.api_drf_drf_internal_failure, container.api_ma_ma_alarm_control, container.api_mhs_mhs_heat_control, container.api_mmi_mmi_interface_failure, container.api_mmi_mmi_lower_alarm_temp, container.api_mmi_mmi_monitor_status, container.api_mmi_mmi_upper_alarm_temp, container.api_mmm_mmm_monitor_mode, container.api_mri_mri_displayed_temp, container.api_mri_mri_interface_failure, container.api_mri_mri_lower_desired_temp, container.api_mri_mri_regulator_status, container.api_mri_mri_upper_desired_temp, container.api_mrm_mrm_regulator_mode, container.api_oip_oit_lower_alarm_tempWstatus, container.api_oip_oit_lower_desired_tempWstatus, container.api_oip_oit_upper_alarm_tempWstatus, container.api_oip_oit_upper_desired_tempWstatus, container.api_sched_schedule, container.api_sched_state)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_cpi_thermostat_current_tempWstatus: $api_cpi_thermostat_current_tempWstatus_strat:expr,
    api_dmf_dmf_internal_failure: $api_dmf_dmf_internal_failure_strat:expr,
    api_drf_drf_internal_failure: $api_drf_drf_internal_failure_strat:expr,
    api_ma_ma_alarm_control: $api_ma_ma_alarm_control_strat:expr,
    api_mhs_mhs_heat_control: $api_mhs_mhs_heat_control_strat:expr,
    api_mmi_mmi_interface_failure: $api_mmi_mmi_interface_failure_strat:expr,
    api_mmi_mmi_lower_alarm_temp: $api_mmi_mmi_lower_alarm_temp_strat:expr,
    api_mmi_mmi_monitor_status: $api_mmi_mmi_monitor_status_strat:expr,
    api_mmi_mmi_upper_alarm_temp: $api_mmi_mmi_upper_alarm_temp_strat:expr,
    api_mmm_mmm_monitor_mode: $api_mmm_mmm_monitor_mode_strat:expr,
    api_mri_mri_displayed_temp: $api_mri_mri_displayed_temp_strat:expr,
    api_mri_mri_interface_failure: $api_mri_mri_interface_failure_strat:expr,
    api_mri_mri_lower_desired_temp: $api_mri_mri_lower_desired_temp_strat:expr,
    api_mri_mri_regulator_status: $api_mri_mri_regulator_status_strat:expr,
    api_mri_mri_upper_desired_temp: $api_mri_mri_upper_desired_temp_strat:expr,
    api_mrm_mrm_regulator_mode: $api_mrm_mrm_regulator_mode_strat:expr,
    api_oip_oit_lower_alarm_tempWstatus: $api_oip_oit_lower_alarm_tempWstatus_strat:expr,
    api_oip_oit_lower_desired_tempWstatus: $api_oip_oit_lower_desired_tempWstatus_strat:expr,
    api_oip_oit_upper_alarm_tempWstatus: $api_oip_oit_upper_alarm_tempWstatus_strat:expr,
    api_oip_oit_upper_desired_tempWstatus: $api_oip_oit_upper_desired_tempWstatus_strat:expr,
    api_sched_schedule: $api_sched_schedule_strat:expr,
    api_sched_state: $api_sched_state_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (
          (api_cpi_thermostat_current_tempWstatus, api_dmf_dmf_internal_failure, api_drf_drf_internal_failure, api_ma_ma_alarm_control, api_mhs_mhs_heat_control, api_mmi_mmi_interface_failure, api_mmi_mmi_lower_alarm_temp, api_mmi_mmi_monitor_status, api_mmi_mmi_upper_alarm_temp, api_mmm_mmm_monitor_mode),
          (api_mri_mri_displayed_temp, api_mri_mri_interface_failure, api_mri_mri_lower_desired_temp, api_mri_mri_regulator_status, api_mri_mri_upper_desired_temp, api_mrm_mrm_regulator_mode, api_oip_oit_lower_alarm_tempWstatus, api_oip_oit_lower_desired_tempWstatus, api_oip_oit_upper_alarm_tempWstatus, api_oip_oit_upper_desired_tempWstatus),
          (api_sched_schedule, api_sched_state)
        ) in (
          ($api_cpi_thermostat_current_tempWstatus_strat, $api_dmf_dmf_internal_failure_strat, $api_drf_drf_internal_failure_strat, $api_ma_ma_alarm_control_strat, $api_mhs_mhs_heat_control_strat, $api_mmi_mmi_interface_failure_strat, $api_mmi_mmi_lower_alarm_temp_strat, $api_mmi_mmi_monitor_status_strat, $api_mmi_mmi_upper_alarm_temp_strat, $api_mmm_mmm_monitor_mode_strat),
          ($api_mri_mri_displayed_temp_strat, $api_mri_mri_interface_failure_strat, $api_mri_mri_lower_desired_temp_strat, $api_mri_mri_regulator_status_strat, $api_mri_mri_upper_desired_temp_strat, $api_mrm_mrm_regulator_mode_strat, $api_oip_oit_lower_alarm_tempWstatus_strat, $api_oip_oit_lower_desired_tempWstatus_strat, $api_oip_oit_upper_alarm_tempWstatus_strat, $api_oip_oit_upper_desired_tempWstatus_strat),
          ($api_sched_schedule_strat, $api_sched_state_strat)
        )
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_cpi_thermostat_current_tempWstatus, api_dmf_dmf_internal_failure, api_drf_drf_internal_failure, api_ma_ma_alarm_control, api_mhs_mhs_heat_control, api_mmi_mmi_interface_failure, api_mmi_mmi_lower_alarm_temp, api_mmi_mmi_monitor_status, api_mmi_mmi_upper_alarm_temp, api_mmm_mmm_monitor_mode, api_mri_mri_displayed_temp, api_mri_mri_interface_failure, api_mri_mri_lower_desired_temp, api_mri_mri_regulator_status, api_mri_mri_upper_desired_temp, api_mrm_mrm_regulator_mode, api_oip_oit_lower_alarm_tempWstatus, api_oip_oit_lower_desired_tempWstatus, api_oip_oit_upper_alarm_tempWstatus, api_oip_oit_upper_desired_tempWstatus, api_sched_schedule, api_sched_state) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
