#include <stdint.h>
#include <stdbool.h>

#include <microkit.h>
#include <sel4/sel4.h>
#include <os/sddf.h>
#include <sddf/timer/client.h>
#include <sddf/timer/config.h>
#include <sddf/util/printf.h>

#include <default.scheduler_config.h>
#include <default.user_config.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

/* Number of nanoseconds in a second */
#define NS_IN_S  1000000000ULL

__attribute__((__section__(".timer_client_config"))) timer_client_config_t config;
__attribute__((__section__(".user_schedule"))) user_schedule_t user_schedule;

uint32_t current_timeslice;

// Bitstring for partition ready status. 0 = not ready, 1 = ready.
uint64_t part_ready;
uint64_t part_ready_check;

bool scheduler_running;

void notify() {
    microkit_channel ch = user_schedule.timeslice_ch[current_timeslice];
    if (ch != 0) { // channel 0 is used to pad out a schedule
        microkit_notify(ch);
    }
    // Set a timeout for the length of this partition's timeslice
    sddf_timer_set_timeout(config.driver_id, user_schedule.timeslices[current_timeslice]);
}

void next_partition() {
    current_timeslice = (current_timeslice + 1) % user_schedule.num_timeslices;
    notify();
}

void notified(microkit_channel ch)
{
    if (ch == config.driver_id) {
        // Timer driver fired — either the initial timeout after all partitions reported
        // ready (starts the schedule) or a periodic tick (advances to the next timeslice).
        if (scheduler_running == false) {
            notify();
            scheduler_running = true;
        } else {
            next_partition();
        }
    } else if ((part_ready_check & (1 << ch)) != 0) { // valid channel belonging to  partition
        if ((part_ready & (1 << ch)) == 0) {
            // Channel not yet marked ready — this is the partition's first notification
            // during the initialisation handshake (before the schedule starts running).

            sddf_dprintf("SCHEDULER | Marking partition %d as ready\n", ch);
            part_ready |= (1 << ch);  // Set this channel's bit in the readiness bitstring

            if (part_ready == part_ready_check) {  // All expected partitions have reported ready
                sddf_dprintf("SCHEDULER | All partitions ready, beginning schedule\n");
                // Timeout to let the last partition become passive before starting
                sddf_timer_set_timeout(config.driver_id, NS_IN_S);
            }
        } else {
            // Runtime signals from partitions are ignored: the schedule is static and each
            // partition runs for its full allotted time regardless of early completion.
        }
    } else {
        sddf_dprintf("SCHEDULER |received unknown notification on channel: %d\n", ch);
    }
}

void init(void)
{
    current_timeslice = 0;

    scheduler_running = false;

    part_ready |= (1 << 0); // ch 0 is always 'ready'
    part_ready_check |= (1 << 0); // ch 0 is always 'ready' -- keeps padding optional

    // Build a bitmask of all channels that must report ready before the schedule
    // can start. Each bit position corresponds to a channel ID. During the
    // initialisation handshake, partitions notify on their channel; part_ready
    // accumulates those bits and is compared against this mask to detect when
    // every scheduled partition has checked in.
    for (int i = 0; i < user_schedule.num_timeslices; i++) {
        part_ready_check |= (1 << user_schedule.timeslice_ch[i]);
    }
}
