#pragma once

#if __has_include("util.h")
#include <util.h>
#elif __has_include("libvmm/util/util.h")
#include <libvmm/util/util.h>
#elif __has_include("sddf/util/util.h")
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#endif

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_upper_alarm_temp(Isolette_Data_Model_Temp_i *data);
bool get_lower_alarm_temp(Isolette_Data_Model_Temp_i *data);
bool put_alarm_control(const Isolette_Data_Model_On_Off *data);
bool get_monitor_mode(Isolette_Data_Model_Monitor_Mode *data);
bool get_current_tempWstatus(Isolette_Data_Model_TempWstatus_i *data);
